### PR TITLE
support custom es host

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@smn review please

**Comment by smn** [comment]
I suspect this isn't going to be the last change for this but let's go ahead & :+1:.

My gut feel is that we'd be better off if we passed in `es` as a parameter and pass that whole sale along to elastic-git so as not to limit us to just the `urls` parameter.

**Comment by smn** [comment]
turned off the coveralls reporting to comments.

**Comment by miltontony** [comment]
@smn changed to dict instead of url

**Comment by smn** [comment]
:+1:

**Pull request merged**
