### PR TITLE
Optionally Expose ES API in unicore.distribute

### PR DESCRIPTION
**Pull request by smn**
Gives us a single (more manageable) source of truth instead of both git (local files) & ES (remote index).

### CODE REVIEW

**Comment by smn** [comment]
Not even close to being ready for review

**Comment by smn** [comment]
@miltontony & @Rizziepit missing tests but this seems to be working.

elasticsearch-py (which elasticutils uses) allows one to set a [`url_prefix`](http://elasticsearch-py.readthedocs.org/en/latest/transports.html?highlight=url_prefix#connection) value which in our case here we'd set to `esapi` (or whatever we settle on).

This way we possibly can continue using large parts of our `EG.workspace()` stuff as is but then point it at a `unicore.distribute` server running somewhere. 

The biggest things that would need to swapping out are the calls that operate on the actual git repository (git pulls, fast-forwards etc...)

**Comment by smn** [comment]
@Rizziepit & @miltontony ready for review.

**Comment by Rizziepit** [comment]
+1. Do you think it is worth having an integration test to check that the config + proxy callable + handler are all glued together correctly?

**Comment by miltontony** [comment]
:+1:  interesting approach

**Comment by smn** [comment]
@Rizziepit maybe, let me check how I'd go about doing that. Any suggestions?

**Comment by Rizziepit** [comment]
I can't think of a way to do it properly without writing utility functions to create ini files, set up WebTest, etc. Perhaps it's good enough to use `config = testing.setUp({'proxy.enabled': 'true'})`, mock `config.add_view` and `config.add_route`, and check that they are called with appropriate arguments when you do `config.include('unicore.distribute.api')`. Might be more effort than it's worth though :)

**Comment by smn** [comment]
@Rizziepit happy with the added test?

**Comment by smn** [comment]
hrm coveralls is complaining. Let me see what's up.

**Comment by Rizziepit** [comment]
Happy!

**Pull request merged**
